#!/bin/sh

docker run --privileged --rm tonistiigi/binfmt --install all

docker buildx create --use default

java_ver=adopt-11

if [ "${DOCKER_TAG#*-}" = "${DOCKER_TAG}" ]; then
    base=${DOCKER_TAG}
    main=
    full=$base
else
    main=${DOCKER_TAG%%-*}
    base=${DOCKER_TAG##*-}
    full=$main-$base
    if [ "${base#*u}" ]; then
        base=${base%%u*}
    fi
    base="$java_ver-$base"
fi

if [ "$full" != "latest" ]; then
    echo "############################################################"
    echo "### pulling latest image, so layer cache is update."
    docker pull $DOCKER_REPO:latest || true
    echo "############################################################"
fi

for layer in "" "python"; do
    if [ "$layer" ]; then
        tag="$layer-$full"
        file="Dockerfile.$layer"
    else
        tag="$full"
        file="Dockerfile"
    fi
    echo "############################################################"
    echo "### building layer '$layer' with tag '$tag'"
    echo "### MAIN_TAG=$main  BASE_TAG=$base FULL_TAG=$full RESULT_TAG=$tag"
    echo "### creating '$DOCKER_REPO:$tag' with '$file'"
    echo "############################################################"

    docker buildx build \
    --build-arg "MAIN_TAG=$main" \
    --build-arg "BASE_TAG=$base" \
    --build-arg "FULL_TAG=$full" \
    --build-arg "RESULT_TAG=$tag" \
    --push \
    --platform linux/amd64,linux/arm64 \
    -t $DOCKER_REPO:$tag \
    -f "$file" .

    res=$?
    if [ $res -ne 0 ]; then
        echo "Building layer $layer returned $res" >&2
        exit $res
    fi
done
